services:
  grafana:
    user: root
    container_name: 'briancullinan-mycomputer-app'

    build:
      context: .
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.5.1}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 4000:3000/tcp
      - 2345:2345/tcp # delve
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - ../dist:/var/lib/grafana/plugins/briancullinan-mycomputer-app
      - ../provisioning:/etc/grafana/provisioning
        ../dist/dashboards:/etc/grafana/provisioning/dashboards/
      - ..:/root/briancullinan-mycomputer-app
      - ./grafana.db:/var/lib/grafana/grafana.db

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.briancullinan-mycomputer-app:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: briancullinan-mycomputer-app
      GF_PATHS_CONFIG: /root/briancullinan-mycomputer-app/grafana.ini
      GF_AUTH_ANONYMOUS_ENABLED: false
      GF_INSTALL_PLUGINS: yesoreyeram-infinity-datasource
      GF_DEFAULT_APP_MODE: development
